### ISSUE TITLE
Add Copying and License

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan-docker-base#25]
There is no information regarding `Copying and License` in this repo like we have in CKAN (https://github.com/ckan/ckan#copying-and-license) and other repositories like https://github.com/ckan/datapusher#license and https://github.com/ckan/ckan-docker#copying-and-license.

**Comment by Gauravp-NEC** [comment]
@kowh-ai, Please let me know your opinion on this issue. I am interest to submit a PR.

**Comment by kowh-ai** [comment]
was merged https://github.com/ckan/ckan-docker/pull/79
