### ISSUE TITLE
Creating webassets_dir in Dockerfile

### ISSUE THREAD

**Issue by stefina** [ckan/ckan-docker-base#27]
I am wondering, whether we should take care of this in the Dockerfile as well and go ahead and create the webassets-directory, see here https://github.com/ckan/ckan-docker-base/pull/26

But, it still will fail with a ```PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/webassets/.webassets-cache'``` so I am not sure when that is supposed to be created.

Would appreciate any hints!

**Comment by kowh-ai** [comment]
Thanks @stefina - I'm not getting any perms problems  at all with the CKAN Docker install...the `ckan:ckan` user owns all the directories it needs to write into and it also runs the ckan processes...what user owns the stuff under `/var/lib/ckan/*` for you?

**Comment by stefina** [comment]
Thank you so much for checking that @kowh-ai ! For me the folder was not created in the first place. Does it exist for you when you build without any changes to the repo? 
For getting ahead, I created the folder but both ways (existing or non-existing) I got a `Permission denied`.
So I am not sure if that is really something that needs to be solved in this project or in CKAN itself, for that I don't know enough about how the webassets work, yet.

**Comment by kowh-ai** [comment]
Hey @stefina - I just tried a brand new [ckan-docker](https://github.com/ckan/ckan-docker) install and all the directories etc are created when the ckan container comes up
![ss1](https://github.com/ckan/ckan-docker-base/assets/54408245/6b9eee54-9fd5-4d63-a2d9-77168c9e7376)

![ss2](https://github.com/ckan/ckan-docker-base/assets/54408245/9301836d-9e59-43a8-a4b4-153aab7d95b6)
