### ISSUE TITLE
Where is setup/supervisor.worker.conf ?

### ISSUE THREAD

**Issue by pdekraker-epa** [ckan/ckan-docker-base#43]
Looking at the [Docker Hub image for ckan-base-xloader](https://hub.docker.com/layers/ckan/ckan-base-xloader/1.0.1/images/sha256-0acbb56551d03a1d074b21398b1aa4e64971569062f4bef384820849d9e60858?context=explore), which I believe is derived from this repository, adds a supervisor.worker.conf file to enable the ckan worker process. I cannot find this file in the repo.

**Comment by kowh-ai** [comment]
@pdekraker-epa - yes you are correct, however it was a one-off at the time and subsequently removed for clarity. However one of the directions _CKAN on Docker_ will be going in the near future is replacing the DataPusher service (image) with XLoader. The work will be done in this repo
