### ISSUE TITLE
 Investigate using DockerHub "Official Images" for python rather than the OS as the base image

### ISSUE THREAD

**Issue by kowh-ai** [ckan/ckan-docker-base#54]
Rather than specifying what OS should be used for the "base image" for CKAN we should target "Official Images" for python

eg: use:`python:3.10-bookworm` for Python 3.10 (latest) on Debian 12 (bookworm)
or `python:3.10-slim` for Python 3.10 (latest) on Debian 12 (slim bookworm)

Please note there are no Ubuntu distributions for Official DockerHub images for Python

Should we use specific **release numbers** ie: `Python 3.10.14` rather than the latest for `Python 3.10`?

**Comment by wardi** [comment]
based on
```
python                          3.10-bookworm     eeec5526d75f   5 weeks ago     1GB
python                          3.10-slim         afa6ddca455a   5 weeks ago     128MB
```
and the fact that we're coming from alpine, I think `slim` is likely a better choice.

**Comment by wardi** [comment]
Don't think it's worth using specific release numbers, the bugfix releases should be compatible
