### ISSUE TITLE
CKAN and Datapusher not listening on IPv6 Interfaces

### ISSUE THREAD

**Issue by dtufood-kihen** [ckan/ckan-docker-base#65]
#### Description

Currently, the CKAN and Datapusher containers are configured to listen only on IPv4 interfaces. This configuration causes commands such as `wget http://localhost:5000` to fail when IPv6 is enabled. The issue arises because CKAN/Datapusher does not listen on the IPv6 loopback interface (`::1`). Given that IPv6 is now the default in Docker, this can lead to connectivity problems.

#### Steps to Reproduce

1. Ensure IPv6 is enabled on your Docker setup (default in Docker v26).
2. Run the CKAN and Datapusher containers.
3. Execute the command: `wget http://localhost:5000`.

#### Expected Behavior

The command should successfully retrieve the web page, indicating that CKAN/Datapusher is listening on both IPv4 and IPv6 interfaces.

#### Actual Behavior

The command fails with an error, indicating that CKAN/Datapusher is not listening on the IPv6 loopback interface. However, `wget http://127.0.0.1:5000` succeeds, confirming that the services are listening on the IPv4 loopback interface.

#### Proposed Solution

To resolve this issue, update the HTTP listeners in the containers from `--http 0.0.0.0:5000` to `--http [::]:5000`. This change ensures that the services listen on all available IPv4 and IPv6 interfaces.

**Comment by amercader** [comment]
Fixed in #67
