### ISSUE TITLE
400 Bad Request The CSRF token is missing

### ISSUE THREAD

**Issue by kowh-ai** [ckan/ckan-docker-base#7]
Logging into a fresh 2.10 CKAN container and try to add a new Organisation you will get a `400 Bad Request The CSRF token is missing` error

![Screenshot 2023-01-27 at 2 39 00 pm](https://user-images.githubusercontent.com/54408245/215100315-b0b88af7-878c-4b84-b097-161fa4a973aa.png)

Workaround is to update the `WTF_CSRF_ENABLED` variable to false in the `ckan.ini` file and then restart the ckan container
![Screenshot 2023-01-27 at 2 41 13 pm](https://user-images.githubusercontent.com/54408245/215100792-a6a7b848-1b84-4d93-bce8-0d54dc96e9a9.png)

Will investigate further, just documenting here

Could be a browser issue - I'm on vanilla Chrome Version 109.0.5414.119 (Official Build) (x86_64)

Tried using Brave (browser)...issue with adding a dataset

**Comment by pdelboca** [comment]
Hello @kowh-ai !

This is because you are setting WTF_CSRF_FIELD_NAME to `csrf_token` but some pieces of the code are hardcoded to `_csrf_token`. I'm working on a fix for this https://github.com/ckan/ckan/pull/7365
