### ISSUE TITLE
Document and implement a new release process

### ISSUE THREAD

**Issue by amercader** [ckan/ckan-docker-base#87]
We should use a more formal process to publish new images to the public repositories to avoid breakages like #86 and release with confidence that the images work (as we release any other artifact basically). Here are some thoughts on how this could look like:

1. Run tests after each PR merge. We can start with the easier ones and improve them later. 
  * Test that the images build fine (this is easy)
  * Test that tests inside the built container work: this is trickier as we need to setup a whole environment. Maybe we can adapt core's [test-environment](https://github.com/ckan/ckan/tree/master/test-infrastructure) scripts
  * Test that the dev images work on Github actions: this is even trickier. We probably need to push the images to a temp repository and start a new workflow that uses them
2. When we are ready to publish new images (including when there are new CKAN releases), i.e. tests are green,  we create [a new release in this repo](https://github.com/ckan/ckan-docker-base/releases/tag/v20241111), listing the changes included
3. Creating a new release triggers a new action to build and push the images to the Docker Hub. This is ready to go in https://github.com/ckan/ckan-docker-base/pull/73 when the current images settle

We could be more strict and limit somehow pushing directly to the Docker Hub

@kowh-ai @wardi how does this sound?

**Comment by kowh-ai** [comment]
Yes all good @amercader - very important that GitHub actions are used to test **dev** images when they are merged into master. 

Maybe we could start using the "**latest**" tag ie: `ckan/ckan-dev:2.11.0.latest` for the newest images for a particular version of CKAN

**Comment by wardi** [comment]
This sounds perfect. I've been leery of merging PRs here because we're missing this process, everything is manual and so many things depend on these images.

Once the process is up and running removing the manual push command would be a great idea.

**Comment by amercader** [comment]
Starting from `v20241125` this new release process is in place
