### ISSUE TITLE
Error building FROM ckan/ckan-dev:2.10.5

### ISSUE THREAD

**Issue by avdata99** [ckan/ckan-docker-base#93]
I'm on an old CKAN project and suddenly stopped building with this error

<pre>
#36 [ckan-devx  1/28] FROM docker.io/ckan/ckan-dev:2.10.5
#36 CACHED

#35 [ckan-devx internal] load build context
#35 transferring context: 1.85kB done
#35 DONE 0.0s

#37 [ckan-devx  2/28] RUN mkdir /docker-entrypoint.d
<b>#37 0.288 mkdir: can't create directory '/docker-entrypoint.d': File exists</b>
#37 ERROR: process "/bin/sh -c mkdir /docker-entrypoint.d" did not complete successfully: exit code: 1
------
 > [ckan-devx  2/28] RUN mkdir /docker-entrypoint.d:
0.288 mkdir: can't create directory '/docker-entrypoint.d': File exists
</pre>

I'm still investigatting

**Comment by kowh-ai** [comment]
Hey @avdata99 - is it possible to update the command to `RUN mkdir -p /docker-entrypoint.d` as this will only create the `/docker-entrypoint.d` directory if if does **not** exist

**Comment by kowh-ai** [comment]
In the meantime are you able to use the python images (`ckan/ckan-dev:2.10.5-py3.10`)  rather than the old alpine images?

**Comment by avdata99** [comment]
Thanks @kowh-ai 
Moving to `ckan/ckan-dev:2.10.5-py3.10` implies a base change from Alpine to Debian which is a big change.
I'm trying to rebuild from a latest version that works for my use case and the make a plan to upgrade to debian

**Comment by avdata99** [comment]
In case is useful for other, I leave two images to use temporary

 - https://hub.docker.com/r/avdata99/ckan-base/tags
 - https://hub.docker.com/r/avdata99/ckan-dev/tags
